#define PLAYTESTERS    "/d/playtesters/"
#define PT_ARMOURY     PLAYTESTERS "handlers/armoury"
#define CHARS          PLAYTESTERS "chars/"
#define ROOMS          PLAYTESTERS "room/"
#define EFFECTS        PLAYTESTERS "effects/"
#define SHADOWS        PLAYTESTERS "effects/"
#define ITEMS          PLAYTESTERS "items/"
#define PT_ROOM_OBJ    ROOMS "pt_room_inherit"
#define PT_ITEM_EFFECT EFFECTS "/pt_item_effect"
