#define CREATOR   "quixadhal"
#define HOME      "/w/quixadhal/"
#define WEAPON    HOME "weapon/"
#define ARMOUR    HOME "armour/"
#define CLOTHES   HOME "clothes/"
#define NPC       HOME "npc/"
#define ITEM      HOME "item/"
#define ROOM      HOME "room/"
#define TEXT      HOME "text/"
