{
  "__STRIP_BEFORE_PROCESS_INPUT__", "",
  "__NO_ADD_ACTION__", "",
  "__NO_LIGHT__", "",
  "__CUSTOM_CRYPT__", "",
  "__PACKAGE_UIDS__", "",
  "__RECEIVE_SNOOP__", "",
  "__ARGUMENTS_IN_TRACEBACK__", "",
  "__NEXT_MALLOC_DEBUG__", "",
  "__ARRAY_STATS__", "",
  "__LOCALS_IN_TRACEBACK__", "",
  "__ED_INDENT_SPACES__", "4",
  "__REF_RESERVED_WORD__", "",
  "__SYSMALLOC__", "",
  "__CFG_MAX_CALL_DEPTH__", "150",
  "__SAVE_EXTENSION__", "\".o\"",
  "__LOG_CATCHES__", "",
  "__PROG_REF_TYPE__", "int",
  "__SMALL_STRING_SIZE__", "100",
  "__CALLOUT_CYCLE_SIZE__", "512",
  "__PACKAGE_MATH__", "",
  "__PACKAGE_DEVELOP__", "",
  "__SUPPRESS_ARGUMENT_WARNINGS__", "",
  "__LARGEST_PRINTABLE_STRING__", "8192",
  "__CFG_LIVING_HASH_SIZE__", "256",
  "__CACHE_STATS__", "",
  "__CONFIG_FILE_DIR__", "\"/home/atuin/bin\"",
  "__TRAP_CRASHES__", "",
  "__RESTRICTED_ED__", "",
  "__STRING_STATS__", "",
  "__HAS_CONSOLE__", "",
  "__CALLOUT_HANDLES__", "",
  "__FLUFFOS__", "",
  "__BINARIES__", "",
  "__CFG_COMPILER_STACK_SIZE__", "600",
  "__LARGE_STRING_SIZE__", "1000",
  "__HEARTBEAT_INTERVAL__", "1",
  "__COMMAND_BUF_SIZE__", "2000",
  "__OLD_ED__", "",
  "__THIS_PLAYER_IN_CALL_OUT__", "",
  "__PACKAGE_CONTRIB__", "",
  "__MALLOC32__", "",
  "__STRUCT_CLASS__", "",
  "__CFG_MAX_LOCAL_VARIABLES__", "50",
  "__MESSAGE_BUFFER_SIZE__", "4096",
  "__NO_WIZARDS__", "",
  "__CFG_MAX_GLOBAL_VARIABLES__", "256",
  "__SAVE_GZ_EXTENSION__", "\".o.gz\"",
  "__PACKAGE_SOCKETS__", "",
  "__NUM_EXTERNAL_CMDS__", "100",
  "__HEART_BEAT_CHUNK__", "32",
  "__MAX_SAVE_SVALUE_DEPTH__", "100",
  "__DEFAULT_PRAGMAS__", "PRAGMA_WARNINGS + PRAGMA_STRICT_TYPES + PRAGMA_ERROR_CONTEXT",
  "__AUTO_SETEUID__", "",
  "__TRACE__", "",
  "__NO_ANSI__", "",
  "__CFG_EVALUATOR_STACK_SIZE__", "3000",
  "__WARN_TAB__", "",
  "__PACKAGE_DWLIB__", "",
  "__APPLY_CACHE_BITS__", "20",
  "__SENSIBLE_MODIFIERS__", "",
  "__MUDLIB_ERROR_HANDLER__", "",
};

#define NUM_OPTION_DEFS 61

